### ISSUE TITLE
[bug] Unable to download specific chapters from manga1001.in but can read in Epic browser.

### ISSUE THREAD

**Issue by kamikaze00007** [dazedcat19/FMD#1339]
### Prerequisites

- [X] I'm using the latest version.
- [X] All website modules are up to date.
- [x] This is not a website module issue.

### System information

Windows 10 22H2 x64

### Describe the bug

I mainly use Epic Browser in its default settings and can confirm I can browse and read all 6 Chapters of this manga there. However, the application can only download Chapter 1 and Chapter 2 for some reason.

Specific Manga in question:
[Manga1001.in 美醜逆転世界で治療師やってます](https://manga1001.in/%e7%be%8e%e9%86%9c%e9%80%86%e8%bb%a2%e4%b8%96%e7%95%8c%e3%81%a7%e6%b2%bb%e7%99%82%e5%b8%ab%e3%82%84%e3%81%a3%e3%81%a6%e3%81%be%e3%81%99-raw-free/)

Chapters the application fail to download:
[Chapter 3](https://manga1001.in/chapters/%e3%80%90%e7%ac%ac3%e8%a9%b1%e3%80%91%e7%be%8e%e9%86%9c%e9%80%86%e8%bb%a2%e4%b8%96%e7%95%8c%e3%81%a7%e6%b2%bb%e7%99%82%e5%b8%ab%e3%82%84%e3%81%a3%e3%81%a6%e3%81%be%e3%81%99-raw/)
[Chapter 4](https://manga1001.in/chapters/%e3%80%90%e7%ac%ac4%e8%a9%b1%e3%80%91%e7%be%8e%e9%86%9c%e9%80%86%e8%bb%a2%e4%b8%96%e7%95%8c%e3%81%a7%e6%b2%bb%e7%99%82%e5%b8%ab%e3%82%84%e3%81%a3%e3%81%a6%e3%81%be%e3%81%99-raw/)
[Chapter 5](https://manga1001.in/chapters/%e3%80%90%e7%ac%ac5%e8%a9%b1%e3%80%91%e7%be%8e%e9%86%9c%e9%80%86%e8%bb%a2%e4%b8%96%e7%95%8c%e3%81%a7%e6%b2%bb%e7%99%82%e5%b8%ab%e3%82%84%e3%81%a3%e3%81%a6%e3%81%be%e3%81%99-raw/)
[Chapter 6](https://manga1001.in/chapters/%e3%80%90%e7%ac%ac6%e8%a9%b1%e3%80%91%e7%be%8e%e9%86%9c%e9%80%86%e8%bb%a2%e4%b8%96%e7%95%8c%e3%81%a7%e6%b2%bb%e7%99%82%e5%b8%ab%e3%82%84%e3%81%a3%e3%81%a6%e3%81%be%e3%81%99-raw/)

For some reason, the application can download these Chapters just fine:
[Chapter 1](https://manga1001.in/chapters/%e3%80%90%e7%ac%ac1%e8%a9%b1%e3%80%91%e7%be%8e%e9%86%9c%e9%80%86%e8%bb%a2%e4%b8%96%e7%95%8c%e3%81%a7%e6%b2%bb%e7%99%82%e5%b8%ab%e3%82%84%e3%81%a3%e3%81%a6%e3%81%be%e3%81%99-raw/)
[Chapter 2](https://manga1001.in/chapters/%e3%80%90%e7%ac%ac2%e8%a9%b1%e3%80%91%e7%be%8e%e9%86%9c%e9%80%86%e8%bb%a2%e4%b8%96%e7%95%8c%e3%81%a7%e6%b2%bb%e7%99%82%e5%b8%ab%e3%82%84%e3%81%a3%e3%81%a6%e3%81%be%e3%81%99-raw/)

### To Reproduce

Trying to download Chapters 3, 4, 5 ,6 always fails for specific manga in Manga1001.in.
Chapter 1 and 2 succeeds.
Using Epic Privacy Browser, I can confirm all chapters are readable.

### Expected behavior

To be able to download all chapters of this manga from Manga1001.in. The application only downloads chapter 1 and 2 and fails the rest of the way for some reason.
